//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mauxnimale_CE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNEE_SALARIE
    {
        public int IDJOURNEESALARIE { get; set; }
        public int IDCOMPTE { get; set; }
        public int IDJOURNEE { get; set; }
        public System.TimeSpan HEUREDEBUT { get; set; }
        public System.TimeSpan HEUREFIN { get; set; }
        public bool CONGE { get; set; }
    
        public virtual JOURNEE JOURNEE { get; set; }
        public virtual SALARIE SALARIE { get; set; }
    }
}
