//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mauxnimale_CE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUITVENDU
    {
        public int IDPRODUIT { get; set; }
        public int IDFACTURE { get; set; }
        public int QUANTITE { get; set; }
    
        public virtual FACTURE_PRODUIT FACTURE_PRODUIT { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
