//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mauxnimale_CE2.api.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOURNEE()
        {
            this.JOURNEE_SALARIE = new HashSet<JOURNEE_SALARIE>();
            this.RENDEZ_VOUS = new HashSet<RENDEZ_VOUS>();
        }
    
        public int IDJOURNEE { get; set; }
        public System.DateTime DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEE_SALARIE> JOURNEE_SALARIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENDEZ_VOUS> RENDEZ_VOUS { get; set; }

        public override string ToString()
        {
            return DATE.Day + "/" + DATE.Month + "/" + DATE.Year;
        }
    }
}
