
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mauxnimale_CE2.api.entities
{

using System;
    using System.Collections.Generic;
    
public partial class LIEN_SOIN
{

    public int LIENID { get; set; }

    public int IDSOIN { get; set; }

    public int IDORDONNANCE { get; set; }



    public virtual ORDONNANCE ORDONNANCE { get; set; }

    public virtual SOIN SOIN { get; set; }

}

}
