//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mauxnimale_CE2.api.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDONNANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDONNANCE()
        {
            this.PRODUITLIES = new HashSet<PRODUITLIES>();
            this.LIEN_SOIN = new HashSet<LIEN_SOIN>();
        }
    
        public int IDORDONNANCE { get; set; }
        public int IDANIMAL { get; set; }
        public string PRESCRIPTION { get; set; }
        public string DIAGNOSTIQUE { get; set; }
        public Nullable<int> IDRDV { get; set; }
    
        public virtual ANIMAL ANIMAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUITLIES> PRODUITLIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIEN_SOIN> LIEN_SOIN { get; set; }
        public virtual RENDEZ_VOUS RENDEZ_VOUS { get; set; }
    }
}
