
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mauxnimale_CE2.api.entities
{

using System;
    using System.Collections.Generic;
    
public partial class SOIN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SOIN()
    {

        this.MALADIE = new HashSet<MALADIE>();

        this.LIEN_SOIN = new HashSet<LIEN_SOIN>();

    }


    public int IDSOINS { get; set; }

    public string DESCRIPTION { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MALADIE> MALADIE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LIEN_SOIN> LIEN_SOIN { get; set; }
        public override string ToString()
        {
            return DESCRIPTION;
        }

    }

}
